# Generated by Django 5.0 on 2024-02-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['is_done', '-created_at'], 'verbose_name': 'tasks', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
